In [1]:
import numpy as np
import pandas as pd

In [2]:
headers=['url','state']
df=pd.read_csv('datathon_train.csv',names=headers)
df.isnull().sum()

url      0
state    0
dtype: int64

In [3]:
df['url']=df['url'].apply(lambda x:x.replace("://"," "))
df['url']=df['url'].apply(lambda x:x.replace("/"," "))
df['url']=df['url'].apply(lambda x:x.replace("."," "))
df['url']=df['url'].apply(lambda x:x.replace("-"," "))
df['url']=df['url'].apply(lambda x:x.replace("%20"," "))
df.head()

url  state
0  https www peoplescollection wales discover wha...      0
1  http yasli sad ru css chase chaseall newinfo_a...      1
2   http denizkent net wp admin js login alibaba com      1
3  http www marketbiz net mbz wp includes js jque...      1
4  http guardiaoitau30horas uniclassdispositivos ...      1

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
vec=v.fit_transform(df['url'])
vec.shape

(100860, 170198)

In [5]:
y=df['state']
y

0         0
1         1
2         1
3         1
4         1
         ..
100855    1
100856    1
100857    0
100858    0
100859    1
Name: state, Length: 100860, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression

In [7]:
x_train,x_test,y_train,y_test=train_test_split(vec,y,test_size=0.0002,random_state=300)
reg=linear_model.LogisticRegression()

In [8]:
reg.fit(x_train,y_train)

C:\Users\samba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [9]:
y_pred=reg.predict(x_test)
print(y_pred)

[1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1]


In [10]:
vec

<100860x170198 sparse matrix of type '<class 'numpy.int64'>'
	with 749492 stored elements in Compressed Sparse Row format>

In [11]:
print(vec)

  (0, 83738)	1
  (0, 166376)	1
  (0, 121702)	1
  (0, 162979)	1
  (0, 59493)	1
  (0, 164575)	1
  (0, 20791)	1
  (0, 129399)	1
  (0, 105616)	1
  (1, 83730)	1
  (1, 167587)	1
  (1, 135712)	1
  (1, 134870)	1
  (1, 54561)	1
  (1, 48436)	1
  (1, 48441)	1
  (1, 112856)	1
  (1, 159343)	1
  (1, 145735)	1
  (1, 122768)	1
  (1, 131365)	1
  (2, 83730)	1
  (2, 57748)	1
  (2, 112463)	1
  (2, 165991)	1
  :	:
  (100857, 76441)	1
  (100857, 54894)	1
  (100857, 140385)	1
  (100857, 158521)	1
  (100857, 142448)	1
  (100857, 126095)	1
  (100857, 5978)	1
  (100857, 24030)	1
  (100858, 166376)	1
  (100858, 83730)	1
  (100858, 140794)	1
  (100858, 141993)	1
  (100858, 114744)	1
  (100859, 166376)	2
  (100859, 83730)	1
  (100859, 122768)	1
  (100859, 100187)	1
  (100859, 29892)	3
  (100859, 51533)	5
  (100859, 135916)	1
  (100859, 65074)	1
  (100859, 26738)	1
  (100859, 100213)	2
  (100859, 167220)	1
  (100859, 70352)	1


In [12]:

from sklearn.metrics import accuracy_score 
print("accuracy",accuracy_score(y_test,y_pred))

accuracy 0.9523809523809523


In [13]:
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 506, 13
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
clf = Ridge(alpha=1.0)
clf.fit(x_test,y_test)
Ridge()

Ridge()

In [14]:
y_pred1=clf.predict(x_test)
print(y_pred1)

[0.93032376 0.06661372 0.04330992 0.01971191 0.86913075 0.00865728
 0.02342776 0.00855984 0.02095871 0.05495709 0.04150052 0.96828744
 0.02342776 0.01547107 0.90113479 0.05143167 0.02095871 0.02095871
 0.93454574 0.02728435 0.94934851]


In [15]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred1))

0.9866420383128773


In [16]:
headers=['web']
df1=pd.read_csv('testing_data.csv',names=headers)
df1.isnull().sum()

web    0
dtype: int64

In [17]:
df1['web']=df1['web'].apply(lambda x:x.replace("://"," "))
df1['web']=df1['web'].apply(lambda x:x.replace("/"," "))
df1['web']=df1['web'].apply(lambda x:x.replace("."," "))
df1['web']=df1['web'].apply(lambda x:x.replace("-"," "))
df=df.apply(lambda x:x.replace("%20"," "))
df1['web']

0                           http www skofija novomesto si 
1        http ferlafashion com saint www loginalibaba c...
2                                   http spatrendonline hu
3                                   http defensasur com ar
4                         http www digitalvd de dvds 37399
                               ...                        
25214                                   http mohaseban org
25215                              https www la croix com 
25216                                  http bit ly 2CbFTLv
25217    http beautyatjessicas com au wp content upload...
25218    http www la taverne des aventuriers com t4575 ...
Name: web, Length: 25219, dtype: object

In [18]:

vec1=v.transform(df1['web'])
vec1.shape

(25219, 170198)

In [19]:
y_pr=reg.predict(vec1)

In [20]:
print(y_pr)

[0 1 0 ... 1 1 0]


In [21]:
final_df=pd.DataFrame()

In [22]:
final_df['a']=y_pr


In [23]:
final_df.to_csv(r'C:\Users\samba\OneDrive\Desktop\datathon 2.o\results6.csv',index=False)

In [24]:
y_pr1=clf.predict(vec1)

In [25]:
print(y_pr1)

[0.00781713 0.14505362 0.16546486 ... 0.16546486 0.31453863 0.04189681]


In [26]:
final_df1=pd.DataFrame()
final_df1['a']=y_pr1
final_df1.to_csv(r'C:\Users\samba\OneDrive\Desktop\datathon 2.o\results1.csv',index=False)

In [27]:
from sklearn import linear_model
lasso = linear_model.Lasso()
lasso.fit(x_test, y_test)

y_pr2= lasso.predict(vec1)

In [28]:
print(y_pr2)

[0.28571429 0.28571429 0.28571429 ... 0.28571429 0.28571429 0.28571429]
